### ISSUE TITLE
Issue https

### ISSUE THREAD

**Issue by medooch** [Atipik/Hoa-WebSocket-Bundle#7]
Hi all,
Does this bundle support ssl certificate ?

I have create my server push, when i communicate my app with the server via http, its work perfectly.
But it's not the case with https ! 

What can i do ? 
i use Mamp Pro on localhost, this is the url of my app, https://ispace:8890/admin/ .
Thanks

**Comment by marmotz** [comment]
This bundle is just a wrapper for Hoa/WebSocket. 
Please, open an issue on https://github.com/hoaproject/Websocket
